export {default as Login } from './Login'
export {default as RegisterPage } from './RegisterPage'
export {default as Profile} from './Profile'
export {default as LikedPage} from './LikedPage'
export {default as MyStorePage} from './MyStorePage' 
export {default as HomePage} from './HomePage' 
export {default as ProductPage} from './ProductPage'